version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - circleci-project-setup
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4e:e4:7e:a5:51:0e:20:27:74:1d:54:0d:6e:5b:71:60"
      - checkout
      - run: echo "A first hello"
      - run: npm -v
      - run: npm install && npm install --only=dev
      - run:
          name: Install
          command: npm install
      - run:
          name: InstallQuasar
          command: sudo npm install -g @quasar/cli
      - run:
          name: Build
          command: quasar build